# Default configurations for training (and subsequent validation)
---
CountNet:
  depth: 4
  in_channels: 3
  out_channels: 1
  fmaps: [32, 64, 64, 128, 256]

Trainer:
  optimizer:
    Adam:
      lr: 0.001
  loss_metric: MSELoss
  loader_train:
    dataset: Mall # UCF_CC_50
    batch_size: 8
    shuffle: True
  loader_test:
    dataset: Mall # ShanghaiTech_A
    batch_size: 8
    shuffle: True
  # tag_ext: small-mall
  # load_from: 200805-151940-small-mall
  validate_run: 200808-105632-mall-inception-depth4-256ft

training:
  epochs: 1
  write_every: 1

validation:
  metrics:
    - MSELoss
    - L1Loss
    - RMSE
    - PSNR
    # - SSIM
