# Default configurations for training and validation
---
CountNet:
  depth: 2
  in_channels: 3
  out_channels: 1
  fmaps: [8, 16]

Trainer:
  optimizer:
    Adam:
      lr: 0.001
  loss_metric: MSELoss
  loader_train:
    dataset: Mall
    batch_size: 16
    shuffle: True
  loader_test:
    dataset: Mall
    batch_size: 16
    shuffle: True

training:
  epochs: 1
  write_every: 1

validation:
  metrics:
    - MSELoss
