# Default configurations for training (and subsequent validation)
---
CountNet:
  depth: 3
  in_channels: 3
  out_channels: 1
  fmaps: [64, 64, 128, 256]

Trainer:
  optimizer:
    Adam:
      lr: 0.001
  loss_metric: MSELoss
  loader_train:
    dataset: Mall # UCF_CC_50
    batch_size: 8
    shuffle: True
  loader_test:
    dataset: Mall # ShanghaiTech_A
    batch_size: 1
    shuffle: True
  # tag_ext: small-mall
  # load_from: 200805-151940-small-mall
  validate_run: 200809-151616-mall-d3-inception

training:
  epochs: 1
  write_every: 1
  validate_every_epoch: bool=False,
  validation_metrics:
    - MAE
    - MSE
    - PSNR
    - GAME

validation:
  metrics:
    - MAE
    - MSE
    - PSNR
    - GAME
