# Default configurations for training and validation
---
CountNet:
  depth: 2
  in_channels: 3
  out_channels: 1
  fmaps: [64, 64, 64]

Trainer:
  optimizer:
    Adam:
      lr: 0.001
  loss_metric: MSELoss
  loader_train:
    dataset: Mall # UCF_CC_50
    batch_size: 8
    shuffle: True
  loader_test:
    dataset: Mall # ShanghaiTech_A
    batch_size: 8
    shuffle: True
  # write_to: output
  # name_ext: small-mall
  # load_from: output/200805-151200-small-mall

training:
  epochs: 10
  write_every: 1

validation:
  metrics:
    - MSELoss
