# Default configurations for training and validation
---
CountNet:
  depth: 2
  in_channels: 3
  out_channels: 1

Trainer:
  optimizer:
    SGD:
      lr: 0.005
  loss_metric: MSELoss
  loader_train:
    dataset: Mall
    batch_size: 8
    shuffle: True
  loader_test:
    dataset: Mall
    batch_size: 8
    shuffle: True

training:
  epochs: 1

validation:
  metrics: