# Default configurations for training and validation
---
CountNet:
  depth: 2
  in_channels: 3
  out_channels: 1
  fmaps: [8, 16]

Trainer:
  optimizer:
    SGD:
      lr: 0.005
  loss_metric: MSELoss
  loader_train:
    dataset: UCF_CC_50
    batch_size: 4
    shuffle: True
  loader_test:
    dataset: UCF_CC_50
    batch_size: 4
    shuffle: True

training:
  epochs: 1

validation:
  metrics:
    - MSELoss
