# Default configurations for training and validation
---
CountNet:
  depth: 5
  in_channels: 3
  out_channels: 1
  fmaps: [16, 16, 32, 32, 32, 64]

Trainer:
  optimizer:
    Adam:
      lr: 0.0001
  loss_metric: MSELoss
  loader_train:
    dataset: ShanghaiTech_A # UCF_CC_50
    batch_size: 8
    shuffle: True
  loader_test:
    dataset: ShanghaiTech_A # ShanghaiTech_A
    batch_size: 4
    shuffle: True

training:
  epochs: 12
  write_every: 2

validation:
  metrics:
    - MSELoss
